
const BusinessType = {
  '1001':'增值税',
  '4001':'企业所得税',
  '2001':'营业税',
  '2002':'房产税',
  '2003':'城镇土地使用税',
  '2004':'印花税',
  '2007':'城市维护建设税',
  '2008':'教育费及附加',
  '2010':'土地增值税',
  '2009':'地方教育附加',
  '2011':'河道管理费',
  '2015':'附加税',
  '2777':'河道维护建设费',
  '2778':'水利建设基金',
  '2779':'副食品价格谁调节基金',
  '2780':'文化事业建设费',
  '2016':'增值税附加',
  '1889':'关账前（进项）',
  '1990':'关账后（进项）',
  '2781':'残疾人就业保障金',
  '1991':'成熟度评价',
  '1992':'关账记录',
  '1993':'不动产进项税',
  '1994':'不动产进项税税金',
  '1995':'预收款税金',
  '1877':'集团分类',
  '1002':'旧的企业所得税',
}

const tblname = {
  't_txbs_erp':'总账',
  't_txbs_house':'房产税',
  't_txbs_stamp':'印花税',
  't_iinv_invoice_line':'增值税进项发票',
  't_oinv_waitprint_inv':'增值税销项发票',
  't_prov_accrued_charge_line':'手工计提日记帐',
  'T_CLOSE_RECORD_PERIOD':'关帐账期表',
  't_form_head':'税金计算申报',
  't_pay_order':'税金支付',
  'T_VIRTUAL_TABLE_ACCRUED':'税金计提',
  'T_HOUSEDUTY_DETAIL':'不动产进项税明细',
  't_plan_payments_detail':'预收款明细',
  't_iinv_invoice_linerate':'发票明细',
  't_business_eas_data':'所得税报账数据',
  't_bussiness_hr_data':'所得税人资数据',
  't_business_fa_data':'所得税资产数据',
}

export {
  BusinessType,
  tblname,
}