/**
 * Created by Administrator on 2018/6/5 0005.
 */

export default [
  {
    id: '31',
    bpid: '3',
    mpid: '3',
    name: '专用发票获取',
  },
  {
    id: '311',
    bpid: '31',
    mpid: '31',
    name: '已获取进项发票管理',
    route: '/entryInvoice/obtainedEntry',
  },
  {
    id: '32',
    bpid: '3',
    mpid: '3',
    name: '发票录入',
  },
  {
    id: '321',
    bpid: '32',
    mpid: '32',
    name: '登记发票信息',
    route: '/entryInvoice/invoiceEntry/registInvoiceInformation',
  },
  {
    id: '322',
    mpid: '32',
    bpid: '32',
    name: '税控认证结算导入及匹配',
    route: '/entryInvoice/invoiceEntry/authentication',
  },
  {
    id: '323',
    mpid: '32',
    bpid: '32',
    name: '红字发票申请查询',
    route: '/entryInvoice/invoiceEntry/creditNote/inquire',
  },
  {
    id: '324',
    mpid: '32',
    bpid: '32',
    name: '登记代扣代缴税收缴款凭证',
    route: '/entryInvoice/invoiceEntry/registerTaxProof',
  },
  {
    id: '325',
    mpid: '32',
    bpid: '32',
    name: '进项税金导入',
    route: '',
  },
  {
    id: '326',
    mpid: '32',
    bpid: '32',
    name: '进项税金批量导入',
    route: '',
  },
  {
    id: '327',
    mpid: '32',
    bpid: '32',
    name: '进项税金批量导入配置',
    route: '',
  },
  {
    id: '33',
    bpid: '3',
    mpid: '3',
    name: '查询统计',
  },
  {
    id: '331',
    mpid: '33',
    bpid: '33',
    name: '获票率统计',
    route: '',
  },
  {
    id: '332',
    mpid: '33',
    bpid: '33',
    name: '发票状态跟踪及预警',
    route: '/entryInvoice/inquiryStatistics/statusWarning',
  },
  {
    id: '34',
    bpid: '3',
    mpid: '3',
    name: '专票认证',
  },
  {
    id: '341',
    mpid: '34',
    bpid: '34',
    name: '发票认证任务池',
    route: '/entryInvoice/specialCertification/invoiceTaskPool',
  },
  {
    id: '342',
    mpid: '34',
    bpid: '34',
    name: '发票认证状态监控',
    route: '/entryInvoice/specialCertification/certification',
  },
  {
    id: '343',
    mpid: '34',
    bpid: '34',
    name: '发票认证日志管理',
    route: '',
  },
  {
    id: '35',
    bpid: '3',
    mpid: '3',
    name: '普票查验',
  },
  {
    id: '351',
    mpid: '35',
    bpid: '35',
    name: '普通发票查验日志管理',
    route: '/entryInvoice/generalTicketInspection/checklog',
  },
]
