export default [
  {
    id: '51',
    bpid: '5',
    mpid: '5',
    name: '税基管理',
  },
  {
    id: '511',
    bpid: '51',
    mpid: '51',
    name: '余额类',
    route: '',
  },
  {
    id: '512',
    bpid: '51',
    mpid: '51',
    name: '印花税',
    route: '/taxManage/taxBase/stampDuty',
  },
  {
    id: '513',
    bpid: '51',
    mpid: '51',
    name: '房产税',
    route: '/taxManage/taxBase/house',
  },
  {
    id: '514',
    bpid: '51',
    mpid: '51',
    name: '城镇土地使用税',
    route: '',
  },
  {
    id: '52',
    bpid: '5',
    mpid: '5',
    name: '税金计算',
  },
  {
    id: '521',
    bpid: '52',
    mpid: '52',
    name: '印花税',
    route: '/taxManage/taxCalculation/stampDuty',
  },
  {
    id: '522',
    bpid: '52',
    mpid: '52',
    name: '房产税',
    route: '/taxManage/taxCalculation/house',
  },
  {
    id: '523',
    bpid: '52',
    mpid: '52',
    name: '附加税',
    route: '/taxManage/taxCalculation/surtax',
  },
  {
    id: '524',
    bpid: '52',
    mpid: '52',
    name: '城镇土地使用税',
    route: '/taxManage/taxCalculation/urbanUseTax',
  },
  {
    id: '525',
    bpid: '52',
    mpid: '52',
    name: '地方税种',
    route: '/taxManage/taxCalculation/localTax',
  },
  {
    id: '526',
    bpid: '52',
    mpid: '52',
    name: '计算表生成监控',
    route: '/taxManage/taxCalculation/tableMonitor',
  },
  {
    id: '53',
    bpid: '5',
    mpid: '5',
    name: '税金计提',
  },
  {
    id: '531',
    bpid: '53',
    mpid: '53',
    name: '计提新增',
    route: '',
  },
  {
    id: '532',
    bpid: '53',
    mpid: '53',
    name: '计提导入',
    route: '/taxManage/accrued/manage',
  },
  {
    id: '533',
    bpid: '53',
    mpid: '53',
    name: '导入凭证日志',
    route: '',
  },
  {
    id: '54',
    bpid: '5',
    mpid: '5',
    name: '税金申报',
  },
  {
    id: '541',
    bpid: '54',
    mpid: '54',
    name: '印花税',
    route: '/taxManage/taxDeclaration/declaration',
  },
  {
    id: '542',
    bpid: '54',
    mpid: '54',
    name: '房产税',
    route: '',
  },
  {
    id: '543',
    bpid: '54',
    mpid: '54',
    name: '地方税种',
    route: '/taxManage/taxDeclaration/localTax',
  },
  {
    id: '55',
    bpid: '5',
    mpid: '5',
    name: '税金支付',
  },
  {
    id: '551',
    bpid: '55',
    mpid: '55',
    name: '生成付款单',
    route: '',
  },
  {
    id: '552',
    bpid: '55',
    mpid: '55',
    name: '付款单查询',
    route: '',
  },

]
