/**
 * Created by Administrator on 2018/6/5 0005.
 */
export default [
  {
    id: '41',
    bpid: '4',
    mpid: '4',
    name: '增值税税基管理',
  },
  {
    id: '411',
    bpid: '41',
    mpid: '41',
    name: '进项发票税基',
    route: '',
  },
  {
    id: '412',
    bpid: '41',
    mpid: '41',
    name: '销项发票税基',
    route: '/vat/taxBase/salesInvoiceTax',
  },
  {
    id: '413',
    bpid: '41',
    mpid: '41',
    name: '预收款明细管理',
    route: '/vat/taxBase/planPayment',
  },
  {
    id: '42',
    bpid: '4',
    mpid: '4',
    name: '增值税计算',
  },
  {
    id: '421',
    bpid: '42',
    mpid: '42',
    name: '增值税销项基础表',
    route: '/vat/calculate/outputTable',
  },
  {
    id: '422',
    bpid: '42',
    mpid: '42',
    name: '增值税进项基础表',
    route: '/vat/calculate/incomeTable',
  },
  {
    id: '423',
    bpid: '42',
    mpid: '42',
    name: '预收款税金计算表',
    route: '',
  },
  {
    id: '424',
    bpid: '42',
    mpid: '42',
    name: '增值税汇总传递单',
    route: '/vat/calculate/summaryTransfer',
  },
  {
    id: '425',
    bpid: '42',
    mpid: '42',
    name: '增值税纳税信息表',
    route: '',
  },
  {
    id: '426',
    bpid: '42',
    mpid: '42',
    name: '增值税纳税信息表接收',
    route: '',
  },
  {
    id: '427',
    bpid: '42',
    mpid: '42',
    name: '增值税纳税信息表汇总',
    route: '/vat/calculate/taxInformationSummary',
  },
  {
    id: '43',
    bpid: '4',
    mpid: '4',
    name: '增值税申报',
  },
  {
    id: '431',
    bpid: '43',
    mpid: '43',
    name: '增值税纳税申报表（属地）',
    route: '/vat/declare/consolidatedReturn',
  },
  {
    id: '432',
    bpid: '43',
    mpid: '43',
    name: '增值税汇总申报表',
    route: '/vat/declare/taxReturn',
  },
  {
    id: '44',
    bpid: '4',
    mpid: '4',
    name: '不动产进项税管理',
  },
  {
    id: '441',
    bpid: '44',
    mpid: '44',
    name: '分期抵扣明细',
    route: '/vat/imPropertyInTax/deductionDetail',
  },
  {
    id: '442',
    bpid: '44',
    mpid: '44',
    name: '分期抵扣汇总',
    route: '/vat/imPropertyInTax/deductionSummary',
  },
  {
    id: '443',
    bpid: '44',
    mpid: '44',
    name: '分期抵扣配置',
    route: '/vat/imPropertyInTax/hirePurchaseConfig',
  },
]
